### ISSUE TITLE
error during dev-build start

### ISSUE THREAD

**Issue by walnutfalls** [ft-interactive/koa2-typescript-boilerplate#1]
npm debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev-server' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]
5 info lifecycle koa2-typescript-boilerplate@1.0.1~predev-server: koa2-typescript-boilerplate@1.0.1
6 silly lifecycle koa2-typescript-boilerplate@1.0.1~predev-server: no script for predev-server, continuing
7 info lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: koa2-typescript-boilerplate@1.0.1
8 verbose lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: unsafe-perm in lifecycle true
9 verbose lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/concubicycle/dev/koa2-typescript-boilerplate/node_modules/.bin:/home/concubicycle/bin:/home/concubicycle/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: CWD: /home/concubicycle/dev/koa2-typescript-boilerplate
11 silly lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: Args: [ '-c', 'nodemon -w lib -x ts-node lib/index.ts' ]
12 info lifecycle koa2-typescript-boilerplate@1.0.1~dev-server: Failed to exec dev-server script
13 verbose stack Error: koa2-typescript-boilerplate@1.0.1 dev-server: `nodemon -w lib -x ts-node lib/index.ts`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid koa2-typescript-boilerplate@1.0.1
15 verbose cwd /home/concubicycle/dev/koa2-typescript-boilerplate
16 error Linux 4.4.0-47-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev-server"
18 error node v7.1.0
19 error npm  v3.10.9
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error koa2-typescript-boilerplate@1.0.1 dev-server: `nodemon -w lib -x ts-node lib/index.ts`
24 error spawn ENOENT
25 error Failed at the koa2-typescript-boilerplate@1.0.1 dev-server script 'nodemon -w lib -x ts-node lib/index.ts'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the koa2-typescript-boilerplate package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     nodemon -w lib -x ts-node lib/index.ts
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs koa2-typescript-boilerplate
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls koa2-typescript-boilerplate
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by aendra-rininsland** [comment]
@concubicycle Please update to the latest version of the boilerplate, this should be solved now.
